<?php

use Mini\Cms\Routing\Route;


/**
 * Implementing hook __pre_assets_build
 * @param array $assets
 * @param string $section_name
 * @param \Mini\Cms\Controller\Route $current_route
 * @return void
 */
function dashboard_pre_assets_build(array &$assets, string $section_name, \Mini\Cms\Controller\Route $current_route): void
{
    /**@var $loaded Route **/
    $loaded = $current_route->getLoadedRoute();
    if($loaded->getRouteId() === 'a7322f9d-3dd0-4be0-8bd4-a156b520b7-42976j-nn5858454') {
        if($section_name == 'footer') {
            $assets[] = "/themes/global/js/simple-datatables/simple-datatables.js";
            $assets[] = "/themes/global/js/main.js";
        }
        if($section_name == 'head') {
            $assets[] = "/themes/global/js/simple-datatables/style.css";
        }
    }
}

